import { Ingredient, IngredientCategory } from "@/app/ingredient/type";

export const mockIngredient: Ingredient[] = [
    {
      key: "1",
      name: "ingredient 1",
      category: "seafood",
      unit: "kg",
      unitPrice: 200,
      productSize:1,
    },
    {
      key: "2",
      name: "ingredient 2",
      category: "meat",
      unit: "g",
      unitPrice: 400,
      productSize:1,
    },
    {
      key: "3",
      name: "ingredient 3",
      category: "seafood",
      unit: "kg",
      unitPrice: 100,
            productSize:1,
    },
    {
      key: "4",
      name: "ingredient 1",
      category: "vegetable",
      unit: "kg",
      unitPrice: 600,
      productSize:1,
    },
    {
      key: "5",
      name: "ingredient 2",
      category: "meat",
      unit: "g",
      unitPrice: 400,
      productSize:1,
    },
    {
      key: "6",
      name: "ingredient 3",
      category: "seafood",
      unit: "kg",
      unitPrice: 100,
      productSize:1,
    },
    {
      key: "7",
      name: "ingredient 1",
      category: "vegetable",
      unit: "kg",
      unitPrice: 600,
      productSize:1,
    },
  ];
  export const ingredienCategorytData: IngredientCategory[] = [
    "seafood",
    "meat",
    "vegetable",
    "other",
  ];
  export const mockMenu = [
    {
      id: "1",
      key: "1",
      name: "menu1",
      cost: 1,
      costPercent: 20,
      yieldPercent: 20,
    },
    {
      id: "2",
      key: "2",
      name: "menu2",
      cost: 2,
      costPercent: 20,
      yieldPercent: 20,
    },
    {
      id: "3",
      key: "3",
      name: "menu3",
      cost: 3,
      costPercent: 20,
      yieldPercent: 20,
    },
    {
      id: "4",
      key: "4",
      name: "menu4",
      cost: 4,
      costPercent: 20,
      yieldPercent: 20,
    },
    {
      id: "5",
      key: "5",
      name: "menu5",
      cost: 5,
      costPercent: 20,
      yieldPercent: 20,
    },
    {
      id: "6",
      key: "6",
      name: "menu6",
      cost: 6,
      costPercent: 20,
      yieldPercent: 20,
    },
  ];